# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70ca2cbe9d57b450f184b3b4774553dab884e0b6e49604ce525b5e10bb135126056d8be1986fa4a0a7b7cc759c7d8038060d5631e531bb7a6d67761b038d2432

test:
  secret_key_base: d8ab8e09918f5880cb4982a9164efa9123e0656ac1a79b64704c92f378cdb55d42bc968234d717ad45e2a72edc18f6eb31b90a424714b80ad4ffa384d4c3617b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d8ab8e09918f5880cb4982a9164efa9123e0656ac1a79b64704c92f378cdb55d42bc968234d717ad45e2a72edc18f6eb31b90a424714b80ad4ffa384d4c3617b
